export const data = [
  {
    Toshkent: [
      "Bektemir tumani",
      "Chilonzor tumani",
      "Hamza tumani",
      "Mirzo Ulug'bek tumani",
      "Mirobod tumani",
      "Sergeli tumani",
      "Shayxontohur tumani",
      "Uchtepa tumani",
      "Yakkasaroy tumani",
      "Yunusobod tumani",
      "Yashnobod tumani",
    ],
  },
  {
    Andijon: [
      "Andijon shahri",
      "Asaka tumani",
      "Baliqchi tumani",
      "Bo'ston tumani",
      "Bulakbashi tumani",
      "Izboskan tumani",
      "Jalolquduq tumani",
      "Marhamat tumani",
      "Oltinko'l tumani",
      "Paxtaobod tumani",
      "Qo'rg'ontepa tumani",
      "Shahrixon tumani",
      "Ulug'nor tumani",
      "Xo'jaobod tumani",
    ],
  },
  {
    Buxoro: [
      "Buxoro shahri",
      "G'ijduvon tumani",
      "Jondor tumani",
      "Kogon tumani",
      "Olot tumani",
      "Peshku tumani",
      "Qorako'l tumani",
      "Qorovulbozor tumani",
      "Romitan tumani",
      "Shofirkon tumani",
      "Vobkent tumani",
    ],
  },
  {
    Fargona: [
      "Farg'ona shahri",
      "Bag'dod tumani",
      "Beshariq tumani",
      "Buvayda tumani",
      "Dang'ara tumani",
      "Farg'ona tumani",
      "Furqat tumani",
      "Qo'qon shahri",
      "Oltiariq tumani",
      "Quva tumani",
      "Rishton tumani",
      "So'x tumani",
      "Toshloq tumani",
      "Uchko'prik tumani",
      "Yozyovon tumani",
    ],
  },
  {
    Jizzax: [
      "Jizzax shahri",
      "Arnasoy tumani",
      "Baxmal tumani",
      "Do'stlik tumani",
      "Forish tumani",
      "G'allaorol tumani",
      "Mirzacho'l tumani",
      "Paxtakor tumani",
      "Yangiobod tumani",
      "Zarbdor tumani",
      "Zafarobod tumani",
      "Zomin tumani",
    ],
  },
  {
    Qashqadaryo: [
      "Qarshi shahri",
      "Chiroqchi tumani",
      "Dehqonobod tumani",
      "G'uzor tumani",
      "Kasbi tumani",
      "Kitob tumani",
      "Koson tumani",
      "Mirishkor tumani",
      "Muborak tumani",
      "Nishon tumani",
      "Shahrisabz shahri",
      "Shahrisabz tumani",
      "Yakkabog' tumani",
    ],
  },
  {
    Navoiy: [
      "Navoiy shahri",
      "Konimex tumani",
      "Karmana tumani",
      "Qiziltepa tumani",
      "Navbahor tumani",
      "Nurota tumani",
      "Tomdi tumani",
      "Uchquduq tumani",
      "Xatirchi tumani",
    ],
  },
  {
    Namangan: [
      "Namangan shahri",
      "Chortoq tumani",
      "Chust tumani",
      "Kosonsoy tumani",
      "Mingbuloq tumani",
      "Norin tumani",
      "Pop tumani",
      "To'raqo'rg'on tumani",
      "Uchqo'rg'on tumani",
      "Uychi tumani",
      "Yangiqo'rg'on tumani",
    ],
  },
  {
    Samarqand: [
      "Samarqand shahri",
      "Bulung'ur tumani",
      "Ishtixon tumani",
      "Jomboy tumani",
      "Kattaqo'rg'on shahri",
      "Kattaqo'rg'on tumani",
      "Narpay tumani",
      "Nurobod tumani",
      "Oqdaryo tumani",
      "Paxtachi tumani",
      "Payariq tumani",
      "Pastdarg'om tumani",
      "Qo'shrabot tumani",
      "Samarqand tumani",
      "Toyloq tumani",
      "Urgut tumani",
    ],
  },
  {
    Surxondaryo: [
      "Termiz shahri",
      "Angor tumani",
      "Bandixon tumani",
      "Boysun tumani",
      "Denov tumani",
      "Jarqo'rg'on tumani",
      "Muzrabot tumani",
      "Oltinsoy tumani",
      "Qiziriq tumani",
      "Qumqo'rg'on tumani",
      "Sariosiyo tumani",
      "Sherobod tumani",
      "Sho'rchi tumani",
      "Termiz tumani",
      "Uzun tumani",
    ],
  },
  {
    Sirdaryo: [
      "Guliston shahri",
      "Boyovut tumani",
      "Guliston tumani",
      "Mirzaobod tumani",
      "Oqoltin tumani",
      "Sayxunobod tumani",
      "Sirdaryo tumani",
      "Xovos tumani",
      "Yangiyer shahri",
      "Sardoba tumani",
    ],
  },
  {
    ToshkentViloyati: [
      "Chirchiq shahri",
      "Angren shahri",
      "Bekobod shahri",
      "Bo'ka tumani",
      "Bo'stonliq tumani",
      "Chinoz tumani",
      "Qibray tumani",
      "Oqqo'rg'on tumani",
      "Ohangaron shahri",
      "Parkent tumani",
      "Piskent tumani",
      "Quyichirchiq tumani",
      "O'rta Chirchiq tumani",
      "Yangiyo'l tumani",
      "Yuqorichirchiq tumani",
      "Zangiota tumani",
    ],
  },
  {
    Xorazm: [
      "Urganch shahri",
      "Bog'ot tumani",
      "Gurlan tumani",
      "Hazorasp tumani",
      "Khiva tumani",
      "Shovot tumani",
      "Urganch tumani",
      "Xonqa tumani",
      "Yangibozor tumani",
      "Yangiariq tumani",
    ],
  },
];
